name: goreleaser

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:  
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      -
        name: Run Tests
        run: |
          go test --coverprofile=coverage.coverprofile --covermode=atomic ./...

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        if: github.ref == 'refs/heads/master'
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false

      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
